# Configuration passed from caller
LIB_FFI ?= libstdio_ffi.a
CC ?= riscv64-unknown-elf-gcc
CFLAGS ?= -O2 -g -march=rv64imac -mabi=lp64 -ffreestanding -nostdlib -mcmodel=medany
LINKER ?= linker.ld
LIB_DIR ?= $(HOME)/.bolt/musl/riscv64-linux-musl/lib
LDFLAGS ?= -T $(LINKER) -nostdlib -static -L $(LIB_DIR) -Wl,--gc-sections
LDLIBS ?= -lc -lgcc
OUTPUT_DIR ?= $(PWD)/build
BIN := $(OUTPUT_DIR)/stdio-c
OBJ := $(OUTPUT_DIR)/main.o

# Targets
all: stdio-c

stdio-c: $(BIN)

$(BIN): $(OBJ) $(LIB_FFI)
	$(CC) $(CFLAGS) $(LDFLAGS) $(OBJ) $(LIB_FFI) $(LDLIBS) -o $(BIN)

$(OBJ): src/main.c | $(OUTPUT_DIR)
	$(CC) $(CFLAGS) -c src/main.c -o $(OBJ)

$(OUTPUT_DIR):
	mkdir -p $(OUTPUT_DIR)

clean:
	rm -f $(OBJ) $(BIN) src/*.o

run: stdio-c
	spike $(BIN)

.PHONY: all clean run stdio-c
